---
version: '3'
###Start Kafka
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
      KAFKA_CLUSTERS_0_ZOOKEEPER: 'zookeeper:2181'

###Start SOS Endpoint
  sos-endpoint-controller:
    image: registry.localdev.me/sos-endpoint-controller:latest
    container_name: sos-endpoint-controller
    ports:
      - "80:8080"
    #entrypoint: tail -F anything
    depends_on:
      - kafka
      - sos-endpoint-initializer
    environment:
      MIL_DIA_MERLIN_MOCKMESSAGE_KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      SERVER_PORT: 8080

  sos-endpoint-initializer:
    image: registry.localdev.me/sos-endpoint-initializer:latest
    container_name: sos-endpoint-initializer
    depends_on:
      - kafka
    environment:
      MIL_DIA_MERLIN_MOCKMESSAGE_KAFKA_BOOTSTRAP_SERVER: "kafka:9092"

###Start SOS Transformer
  sos-transformer-service:
    image: registry.localdev.me/sos-transformer-service:latest
    container_name: sos-transformer-service
    depends_on:
      - kafka
      - sos-transformer-initializer
    environment:
      MIL_DIA_MERLIN_SOS_KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      MIL_DIA_MERLIN_SOS_KAFKA_PARTITION_COUNT: 1
      MIL_DIA_MERLIN_SOS_KAFKA_REPLICA_COUNT: 1

  sos-transformer-initializer:
    image: registry.localdev.me/sos-transformer-initializer:latest
    container_name: sos-transformer-initializer
    depends_on:
        - kafka
    environment:
      MIL_DIA_MERLIN_SOS_KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      MIL_DIA_MERLIN_SOS_KAFKA_PARTITION_COUNT: 1
      MIL_DIA_MERLIN_SOS_KAFKA_REPLICA_COUNT: 1

###Start MERLIN UI
  merlin-ui:
    image: registry.localdev.me/merlin-ui:latest
    container_name: merlin-ui
    ports:
      - "3000:3000"